baseURL = 'https://www.ghaaspoos.com'
languageCode = 'en-us'
title = 'Ghaaspoos'
theme = "PaperMod"

[author]
  name = "Raj"

[params]
  defaultTheme = "light"
  disableThemeToggle = false
  description = "A fresh perspective on geopolitics, technology, and finance"

  [params.assets]
    theme_color = "#7cb342"
    msapplication_TileColor = "#1b5e20"

  [params.label]
    text = "Ghaaspoos"

  [params.homeInfoParams]
    Title = "Ghaaspoos"
    Content = "A common man's field of thought 🤔"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]
