baseURL = 'https://www.ghaaspoos.com'
languageCode = 'en-us'
title = 'Ghaaspoos'
theme = "PaperMod"

[author]
  name = "Raj"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]
